logging:
  level:
    root: info
    org.springframework.web: info
    org.springframework.security: debug
    org.springframework.security.oauth2: debug
    org.springframework.boot.autoconfigure: info

spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: replaceMe
            client-secret: replaceMe
          github:
            clientId: replaceMe
            clientSecret: replaceMe
        provider:
          okta:
            authorization-uri: https://dev-314418.okta.com/oauth2/default/v1/authorize
            token-uri: https://dev-314418.okta.com/oauth2/default/v1/token
            user-info-uri: https://dev-314418.okta.com/oauth2/default/v1/userinfo
            jwk-set-uri: https://dev-314418.okta.com/oauth2/default/v1/keys